### ISSUE TITLE
checkpint key conflict

### ISSUE THREAD

**Issue by NKdryer** [shanemankiw/Panodiff#3]
When I run test_on_simpleset.py and load norota_clean.ckpt downloaded by your link, I get this error：
**RuntimeError: Error(s) in loading state_dict for No_Rota_Inpaint:
        Unexpected key(s) in state_dict: "cond_stage_model.transformer.text_model.embeddings.position_ids".**

**Comment by shanemankiw** [comment]
Hi, it seems like this is an issue with the FrozenCLIPEmbedder's state_dict. Can I see a full log?
Also, did you change FrozenCLIPEmbedder's configs? the version we use is "openai/clip-vit-large-patch14"
