### ISSUE TITLE
Question in mask_path = 'datasets/90binarymask.png'

### ISSUE THREAD

**Issue by RYYAI** [shanemankiw/Panodiff#5]
Under 

./Panodiff/dataloaders/rota_dataset.py

# TODO: add these paths when ziyu told me to.
mask_path = 'datasets/90binarymask.png'

Sorry, I didn't find mask_path = 'datasets/90binarymask.png' in the repo.
What's this and how can I find it ? And What for?

**Comment by shanemankiw** [comment]
It is a binary mask indicating the region in panorama that, 90 degree FoV with no rotation,  covers. It looks like this:
![90binarymask](https://github.com/shanemankiw/Panodiff/assets/34244000/706919c9-9c1f-4127-baae-68a268bf3920)
It is used if we are trying to input a 90 degree FoV with no rotation and outpaint the rest.
