### ISSUE TITLE
预训练模型和数据集链接失效，无法下载

### ISSUE THREAD

**Issue by Fengxixiaom** [shanemankiw/Panodiff#6]
您好，对您的工作非常感兴趣。但是目前是预训练模型和数据集都没有办法下载，您能重新提供有效的链接嘛？

**Comment by shanemankiw** [comment]
你好，我刚更新了链接，请用这个
https://tamucs-my.sharepoint.com/:u:/g/personal/jionghao_tamu_edu/Eab8PmPlexdIntvYemT3LMMBxWdQyi7G6GmTztIboH8nSA?e=2oo1xC

> 您好，对您的工作非常感兴趣。但是目前是预训练模型和数据集都没有办法下载，您能重新提供有效的链接嘛？
